[package]
name = "fan_remote"
version = "0.1.0"
authors = ["Stephan Sokolow <http://www.ssokolow.com/ContactMe>"]
edition = "2018"

[dependencies]
actix-web = { version = "4.1.0", default-features = false }
gumdrop = "0.8.1"
thiserror = "1.0.31"
notify-rust = { version = "4.5.8", optional = true }
listenfd = "1.0.0"

[profile.dev.package."*"]
# Set the default for dependencies in Development mode.
opt-level = 3

[profile.dev]
# Turn on a small amount of optimization in Development mode.
opt-level = 1

[features]
default = ["notify-rust"]
